management:
  endpoints:
    web:
      exposure:
        include: "*"
#spring:
#  learn:
#    data:
#      base-dir: "json"
spring:
  learn:
    data:
      order-locations:
        - file
        - classpath